import {
  MigrationInterface,
  QueryRunner,
} from 'typeorm';

export class InitialSchema1710000000000
  implements MigrationInterface
{
  async up(
    _queryRunner: QueryRunner,
  ): Promise<void> {
    /*
     * Schema is generated by TypeORM in development;
     * keep this migration slot for production DDL.
     */
  }

  async down(
    _queryRunner: QueryRunner,
  ): Promise<void> {
  }
}